name: navigation
publish_to: none

environment:
  sdk: ">=2.17.1 <3.3.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^7.8.4
  get_it: ^7.6.4
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  auth:
    path: ../feature/auth
  analyzer: ^6.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  auto_route_generator: 7.3.2
  build_runner: ^2.4.7