// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnpmHCWb_VwbESTixx_E-Huga7TZU3wA',
    appId: '1:624583568538:web:cd70e6078cf8158e88c323',
    messagingSenderId: '624583568538',
    projectId: 'chatapp-a0b76',
    authDomain: 'chatapp-a0b76.firebaseapp.com',
    storageBucket: 'chatapp-a0b76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ypiaZxGzKgAuamGhAH175JBOql0k6NQ',
    appId: '1:624583568538:android:a82b1bb55e3eb1d288c323',
    messagingSenderId: '624583568538',
    projectId: 'chatapp-a0b76',
    storageBucket: 'chatapp-a0b76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdHICoc5ARTrYieHLD2jz1zej1FcDTxk',
    appId: '1:624583568538:ios:7750b38f4597395a88c323',
    messagingSenderId: '624583568538',
    projectId: 'chatapp-a0b76',
    storageBucket: 'chatapp-a0b76.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdHICoc5ARTrYieHLD2jz1zej1FcDTxk',
    appId: '1:624583568538:ios:bbc89cc96d8d853588c323',
    messagingSenderId: '624583568538',
    projectId: 'chatapp-a0b76',
    storageBucket: 'chatapp-a0b76.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
