name: auth
description: Auth feature
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.1 <4.1.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  data:
    path: ../../data
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui
  home:
    path: ../../feature/home
  navigation:
    path: ../../navigation
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  auto_route:  ^7.8.4
  auto_route_generator: ^7.3.2
  #animated_splash_screen: ^1.3.0
 # page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6


flutter: